In [111]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import classification_report,confusion_matrix

In [12]:
data = pd.read_csv("iris.csv") #read data

In [18]:
output_y = data.iristype #select output col
input_x = data.drop ("iristype", axis = 1) #select input col

In [22]:
#split the data into training and test set
X_train, X_test, y_train, y_test = train_test_split(input_x, output_y, test_size=0.2, random_state=123, stratify=output_y)

In [135]:
#crossvalidation pipeline
pipeline = make_pipeline (MLPClassifier(max_iter=100, solver = 'lbfgs'))

In [149]:
#hyperparameters for classifier
hyperParameter = {'mlpclassifier__hidden_layer_sizes': [5, 10],
                  'mlpclassifier__activation': ['tanh', 'relu'],
                  'mlpclassifier__alpha': [0.00001, 0.0005]
}

In [150]:
#crossvalidation
clf = GridSearchCV(pipeline, hyperParameter, n_jobs = -1, cv=10)

In [151]:
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Pipeline(memory=None,
                                steps=[('mlpclassifier',
                                        MLPClassifier(activation='relu',
                                                      alpha=0.0001,
                                                      batch_size='auto',
                                                      beta_1=0.9, beta_2=0.999,
                                                      early_stopping=False,
                                                      epsilon=1e-08,
                                                      hidden_layer_sizes=(100,),
                                                      learning_rate='constant',
                                                      learning_rate_init=0.001,
                                                      max_iter=100,
                                                      momentum=0.9,
                             

In [152]:
print (clf.best_params_)

{'mlpclassifier__activation': 'tanh', 'mlpclassifier__alpha': 1e-05, 'mlpclassifier__hidden_layer_sizes': 5}


In [153]:
#predict
y_predtrain = clf.predict(X_train)

In [154]:
#Evaluate
print (confusion_matrix(y_train, y_predtrain))

[[40  0  0]
 [ 0 39  1]
 [ 0  0 40]]


In [155]:
print (classification_report(y_train, y_predtrain))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        40
Iris-versicolor       1.00      0.97      0.99        40
 Iris-virginica       0.98      1.00      0.99        40

       accuracy                           0.99       120
      macro avg       0.99      0.99      0.99       120
   weighted avg       0.99      0.99      0.99       120



In [156]:
y_pred = clf.predict(X_test)

In [157]:
print (confusion_matrix(y_test, y_pred))

[[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]


In [158]:
print (classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.80      0.89        10
 Iris-virginica       0.83      1.00      0.91        10

       accuracy                           0.93        30
      macro avg       0.94      0.93      0.93        30
   weighted avg       0.94      0.93      0.93        30

